[build]
command = "npm run build:client"
functions = "netlify/functions"
publish = "dist/spa"


[functions]
external_node_modules = ["@prisma/client", ".prisma"]
included_files = ["node_modules/@prisma/client/**", "node_modules/.prisma/**"]
node_bundler = "esbuild"
[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
